
__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd.yml',
]


output_dir: ./output/rtdetr_r9vd_6x_coco

PResNet:
  variant: a
  depth: 9
  freeze_at: -1
  freeze_norm: False
  pretrained: False 

HybridEncoder:
  in_channels: [64, 96, 128]
    #[128, 256, 512]
  hidden_dim: 128
    #256
  expansion: 0.5


RTDETRTransformer:
  eval_idx: -1
  num_decoder_layers: 2 
    #3
  num_denoising: 100
  hidden_dim: 128
  d_model: 128
  feat_channels: [128,128,128]

optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?=.*norm).*$'
      lr: 0.00001
      weight_decay: 0.
    - 
      params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.00001
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bias)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

