
__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetr_r50vd.yml',
]

RTDETR: 
  backbone: TorchvisionNet
  encoder: HybridEncoder
  decoder: RTDETRTransformer
  multi_scale: [480, 512, 544, 576, 608, 640, 640, 640, 672, 704, 736, 768, 800]

output_dir: ./output/mobilenet_6x_coco

TorchvisionNet:
  name: squeezenet1_1
  freeze_at: -1
  freeze_norm: False
  pretrained: False
  out_indices: [2, 3, 4]
  out_names: ["features.10.cat", "features.11.cat", "features.12.cat"]
HybridEncoder:
  in_channels: [16, 32, 112]
    #[128, 256, 512]
  hidden_dim: 128
    #256
  expansion: 0.5


RTDETRTransformer:
  eval_idx: -1
  num_decoder_layers: 2 
    #3
  num_denoising: 100
  hidden_dim: 128
  d_model: 128
  feat_channels: [128,128,128]

optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?=.*norm).*$'
      lr: 0.00001
      weight_decay: 0.
    - 
      params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.00001
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bias)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

